<a href="https://colab.research.google.com/github/dharmeshrohit/pydata-book/blob/main/numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Creating Numpy Arrays

In [180]:
import numpy as np

In [181]:
# np.array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [182]:
# 2D and 3D
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [183]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10], [11,12]]])
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [184]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [185]:
# np.arange
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [186]:
# with reshape
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [187]:
a = np.arange(12)
#a.reshape(3, -1)   # becomes (3,4)
a.reshape(-1, 2)   # becomes (6,2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [188]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [189]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [190]:
# np.random
np.random.random((2,2))

array([[0.30774037, 0.6451634 ],
       [0.12430301, 0.04024191]])

In [191]:
# np.linspace
np.linspace(1, 5, 20, dtype=int)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5])

In [192]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Array Attributes

In [193]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [194]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [195]:
a3.ndim

3

In [196]:
# shape
print(a2.shape)

(3, 4)


In [197]:
# size
print(a1.size)

10


In [198]:
# itemssize
a1.itemsize

4

In [199]:
# nbytes
a2.nbytes

96

In [200]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [201]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [202]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
# Scaler Operations
# Arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [205]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [206]:
# Vector Operations
# arithmetic
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [207]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[99., 80., 27.],
       [89., 66., 34.],
       [11., 20., 95.]])

In [208]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.min(a1, axis=1)

array([27., 34., 11.])

In [209]:
# mean/median/std/var
np.std(a1, axis=1)

array([30.46673961, 22.55363977, 37.65634077])

In [210]:
# trigonomoetrix function
np.sin(a1)

array([[-0.99920683, -0.99388865,  0.95637593],
       [ 0.86006941, -0.02655115,  0.52908269],
       [-0.99999021,  0.91294525,  0.68326171]])

In [211]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [212]:
# log and exponets
np.exp(a1)

array([[9.88903032e+42, 5.54062238e+34, 5.32048241e+11],
       [4.48961282e+38, 4.60718663e+28, 5.83461743e+14],
       [5.98741417e+04, 4.85165195e+08, 1.81123908e+41]])

In [213]:
# round/floor/ceil/trunc

np.trunc(np.random.random((2,3))*100)

array([[15.,  2., 89.],
       [50., 19., 28.]])

### Indexing and Slicing

In [214]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [217]:
a2[0:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [218]:
a3[1,0:,1:]

array([[5],
       [7]])

In [219]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
a1[1:8:4]

array([1, 5])

In [221]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [223]:
a2[1:,1::2]

array([[ 5,  7],
       [ 9, 11]])

In [224]:
a2[::2,0::2]

array([[ 0,  2],
       [ 8, 10]])

In [225]:
a2[1:,::3]

array([[ 4,  7],
       [ 8, 11]])

In [226]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [227]:
a3 = np.arange(27).reshape(3,3,3)

In [228]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [229]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [230]:
a3[::2,1,::2]

array([[ 3,  5],
       [21, 23]])

In [231]:
a3[1::,0,1:]

array([[10, 11],
       [19, 20]])

In [232]:
a3[0:,2, 1:]

array([[ 7,  8],
       [16, 17],
       [25, 26]])

### Iterating

In [233]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [234]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [235]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [236]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [237]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## reshaping



In [238]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [239]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [240]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [179]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [241]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [242]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [243]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [244]:
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splittin

In [246]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [250]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [251]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [252]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]