<a href="https://colab.research.google.com/github/dharmeshrohit/pydata-book/blob/main/Numpy-advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy array vs Python lists

In [9]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []

import time
start = time.time()
# Iterate up to the length of the shorter list
for i in range(min(len(a), len(b))):
  c.append(a[i] + b[i])
print(time.time()-start)

1.8479726314544678


In [10]:
# numpy
import numpy as np
a = np.arange(100000000)
b = np.arange(100000000, 200000000)

start = time.time()
c = a + b
print(time.time()-start)

0.5193407535552979


In [11]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [14]:
a = np.arange(10000000, dtype=np.int8)
sys.getsizeof(a)

10000112

## Advance Indexing

In [15]:
# Normal Indexing and Slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a[1,2]

np.int64(6)

In [20]:
a[1:2,1:3]

array([[5, 6]])

In [36]:
# Fancy Indexing

a[[0,2,3],:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[38, 12, 57, 73],
       [86, 26, 59, 81],
       [91, 91,  8, 27],
       [42, 43, 14, 59],
       [44, 82, 38, 58],
       [82,  1, 46, 48]])

In [38]:
# Find all numbers greater than 50
a[a > 50]

array([57, 73, 86, 59, 81, 91, 91, 59, 82, 58, 82])

In [41]:
# Find out even numbers
a[a % 2 == 0]

array([38, 12, 86, 26,  8, 42, 14, 44, 82, 38, 58, 82, 46, 48])

In [42]:
# find all numbers greater than 50 and are even
a[(a > 50) & (a % 2 == 0)]

array([86, 82, 58, 82])

In [43]:
# find all number not divisible by 7
a[~(a % 7 == 0)]

array([38, 12, 57, 73, 86, 26, 59, 81,  8, 27, 43, 59, 44, 82, 38, 58, 82,
        1, 46, 48])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [44]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [45]:
# diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

In [46]:
print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [47]:
# more examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [48]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)

print(a+b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [49]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [50]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [51]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [52]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [53]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 