<a href="https://colab.research.google.com/github/dharmeshrohit/pydata-book/blob/main/Numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ## np.sort
 Rturn a sorted copy of an array

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [ ]:
b

array([[91, 74, 39, 87],
       [11,  4, 50, 86],
       [85, 42, 40, 71],
       [12, 30, 85, 30],
       [ 1, 35, 31,  2],
       [61, 58, 14, 81]])

In [ ]:
np.sort(a)[::-1]

array([99, 97, 80, 52, 48, 43, 42, 41, 31, 31, 30, 27, 20, 13,  1])

In [ ]:
np.sort(b, axis=0)

array([[ 1,  4, 14,  2],
       [11, 30, 31, 30],
       [12, 35, 39, 71],
       [61, 42, 40, 81],
       [85, 58, 50, 86],
       [91, 74, 85, 87]])

## np.append
The numpy,append() appends values along th mentioned axis at the end of the array

In [ ]:
np.append(a,200)

array([ 31,   1,  48,  31,  80,  42,  13,  27,  52,  43,  99,  97,  30,
        20,  41, 200])

In [ ]:
b

array([[91, 74, 39, 87],
       [11,  4, 50, 86],
       [85, 42, 40, 71],
       [12, 30, 85, 30],
       [ 1, 35, 31,  2],
       [61, 58, 14, 81]])

In [ ]:
np.append(b, np.random.random((b.shape[0],1)),axis=1)

array([[91.        , 74.        , 39.        , 87.        ,  0.3258596 ],
       [11.        ,  4.        , 50.        , 86.        ,  0.83208221],
       [85.        , 42.        , 40.        , 71.        ,  0.88825449],
       [12.        , 30.        , 85.        , 30.        ,  0.16789041],
       [ 1.        , 35.        , 31.        ,  2.        ,  0.32835627],
       [61.        , 58.        , 14.        , 81.        ,  0.25978292]])

## np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique
With the help of np.unique() method, we can get the unique values from array given as parameter in np.unique() method.

In [ ]:
e = np.array([1,1,2,2,3,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims
With the help of numpy.expand_dims() method, we can get the expanded dimenstions of an array.

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[31],
       [ 1],
       [48],
       [31],
       [80],
       [42],
       [13],
       [27],
       [52],
       [43],
       [99],
       [97],
       [30],
       [20],
       [41]])

## np.where
The `numpy.where()` function returns the indices of elements in an input array where the given condition is satisfied

In [ ]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [ ]:
# Find all indices with value greater than 50
np.where(a>50)

(array([ 4,  8, 10, 11]),)

In [33]:
 # replace all values > 50 with 0
 np.where(a>50,0,a)

array([31,  1, 48, 31,  0, 42, 13, 27,  0, 43,  0,  0, 30, 20, 41])

In [31]:
np.where(a%2==0,0,a)

array([31,  1,  0, 31,  0,  0, 13, 27,  0, 43, 99, 97,  0,  0, 41])

## np.argmax
The numpy.argmax() function returns indixes of the max element of the array in a particular axis.

In [34]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [35]:
np.argmax(a)

np.int64(10)

In [36]:
b

array([[91, 74, 39, 87],
       [11,  4, 50, 86],
       [85, 42, 40, 71],
       [12, 30, 85, 30],
       [ 1, 35, 31,  2],
       [61, 58, 14, 81]])

In [39]:
np.argmax(b, axis=1)

array([0, 3, 0, 2, 1, 3])

In [41]:
# np.argmin
np.argmin(b,axis=0)

array([4, 1, 5, 4])

# np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elemets over a given axis

In [42]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [43]:
np.cumsum(a)

array([ 31,  32,  80, 111, 191, 233, 246, 273, 325, 368, 467, 564, 594,
       614, 655])

In [49]:
b

array([[91, 74, 39, 87],
       [11,  4, 50, 86],
       [85, 42, 40, 71],
       [12, 30, 85, 30],
       [ 1, 35, 31,  2],
       [61, 58, 14, 81]])

In [50]:
np.cumsum(b, axis=1)

array([[ 91, 165, 204, 291],
       [ 11,  15,  65, 151],
       [ 85, 127, 167, 238],
       [ 12,  42, 127, 157],
       [  1,  36,  67,  69],
       [ 61, 119, 133, 214]])

In [51]:
# np.cumprod
np.cumprod(a)

array([                  31,                   31,                 1488,
                      46128,              3690240,            154990080,
                 2014871040,          54401518080,        2828878940160,
            121641794426880,    12042537648261120,  1168126151881328640,
       -1849703590979244032,  -100583672165777408, -4123930558796873728])

## np.percentile
numpy.percentile() function used to compute the nth percentile of the given data (array element) along the specified axis.

In [52]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [61]:
np.percentile(a,50)

np.float64(41.0)

In [60]:
np.median(a)

np.float64(41.0)

## np.histogeam
Numpy has a built-in numpy.histogram()function which represent the frequence of the data distribution in the graphical form

In [62]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [65]:
np.histogram(a, bins=[0,50,100])

(array([11,  4]), array([  0,  50, 100]))

## np.corrcoef
Return Pearson Prodcut-moment correlation coefficients.

In [66]:
salary =np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin
with the help of numpy.isin() method, we ca see that one array having valuas are checked in a different numpy array having different elements with different sizes.

In [67]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [68]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([80, 30, 20])

## np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [69]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [70]:
np.flip(a)

array([41, 20, 30, 97, 99, 43, 52, 27, 13, 42, 80, 31, 48,  1, 31])

In [71]:
b

array([[91, 74, 39, 87],
       [11,  4, 50, 86],
       [85, 42, 40, 71],
       [12, 30, 85, 30],
       [ 1, 35, 31,  2],
       [61, 58, 14, 81]])

In [72]:
np.flip(b)

array([[81, 14, 58, 61],
       [ 2, 31, 35,  1],
       [30, 85, 30, 12],
       [71, 40, 42, 85],
       [86, 50,  4, 11],
       [87, 39, 74, 91]])

## np.put()
The `numpy.put()` function replaces specific element of an array with give values of p_array. Array indexed works on flattened array.

In [73]:
a

array([31,  1, 48, 31, 80, 42, 13, 27, 52, 43, 99, 97, 30, 20, 41])

In [84]:
np.put(a,[0],[1100])

In [85]:
a

array([1100,  530,  530,   31,   80,  530,   13,   27,   52,   43,   99,
         97,   30,   20,   41])

## np.delete
The `numpy.delete()` function rerurns a new array with the deletion of sub-array along with the mentioned axis.

In [86]:
a

array([1100,  530,  530,   31,   80,  530,   13,   27,   52,   43,   99,
         97,   30,   20,   41])

In [88]:
np.delete(a,[0,1,6])

array([530,  31,  80, 530,  27,  52,  43,  99,  97,  30,  20,  41])

## Set functions
 - np.union1d
 - np.interesect1d
 - np.setdiff1d
 - np.setxor1d
 - np.in1d

In [90]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
np.intersect1d(m,n)

array([3, 4, 5])

In [92]:
np.setdiff1d(m,n)

array([1, 2])

In [93]:
np.setdiff1d(n,m)

array([6, 7])

In [94]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [97]:
m[np.in1d(m,5)]

/tmp/ipython-input-1689066636.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,5)]


array([5])

## np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

In [98]:
a

array([1100,  530,  530,   31,   80,  530,   13,   27,   52,   43,   99,
         97,   30,   20,   41])

In [100]:
np.clip(a, a_min=25,a_max=75)

array([75, 75, 75, 31, 75, 75, 25, 27, 52, 43, 75, 75, 30, 25, 41])